media:
  input: public/assets
  output: public/assets
  categories: [ "image" ]
content:
  - name: home-page
    label: Home Page
    type: file
    format: json
    path: "content/home-page.json"
    view:
      fields: [ coverImage, title, date ]
    fields:
      - name: sections
        label: Sections
        type: block
        list: true
        blocks:
          - name: hero
            label: Hero Section
            type: object
            fields:
              - { name: label, label: Label, type: string }
              - { name: title, label: Title, type: string }
              - { name: id, label: id, type: string }
              - { name: subtitle, label: Subtitle, type: string }
              - { name: description, label: Description, type: string }
              - { name: image, label: Image, type: image }
              - { name: imageAlt, label: Image Alt, type: string }
              - { name: ctaText, label: CTA Text, type: string }
              - { name: ctaLink, label: CTA Link, type: string }
          - name: functions
            label: Platform Functions
            type: object
            fields:
              - { name: label, label: Label, type: string }
              - { name: name, label: Name, type: string }
              - { name: id, label: id, type: string }
              - { name: title, label: Title, type: string }
              - { name: subtitle, label: Subtitle, type: string }
              - name: features
                label: Features
                type: block
                list: true
                blocks: 
                  - name: feature
                    label: Feature
                    fields:
                      - name: title
                        label: Title
                        type: string
                      - name: description
                        label: Description
                        type: string
                      - name: emoji
                        label: Emoji
                        type: string
              - { name: image, label: Image, type: image }
              - { name: imageAlt, label: Image Alt, type: string }
          - name: use-cases
            label: Use Cases by Industry
            type: object
            fields:
              - { name: label, label: Label, type: string }
              - { name: id, label: id, type: string }
              - { name: title, label: Title, type: string }
              - { name: subtitle, label: Subtitle, type: string }
              - { name: image, label: Image, type: image }
              - { name: imageAlt, label: Image Alt, type: string }
              - name: cases
                label: Use Cases
                type: block
                list: true
                blocks:
                  - name: case
                    label: Use Case
                    fields:
                      - name: title
                        label: Title
                        type: string
                      - name: description
                        label: Description
                        type: string
                      - name: emoji
                        label: Emoji
                        type: string
          - name: key-features
            label: Key Features
            type: object
            fields:
              - { name: label, label: Label, type: string }
              - { name: id, label: id, type: string }
              - { name: title, label: Title, type: string }
              - name: features
                label: Features
                type: block
                list: true
                blocks:
                  - name: feature
                    label: Feature
                    fields:
                      - name: title
                        label: Title
                        type: string
                      - name: description
                        label: Description
                        type: string
                      - name: emoji
                        label: Emoji
                        type: string
          - name: how-it-works
            label: How It Works
            type: object
            fields:
              - { name: label, label: Label, type: string }
              - { name: id, label: id, type: string }
              - { name: title, label: Title, type: string }
              - name: steps
                label: Steps
                type: block
                list: true
                blocks:
                  - name: step
                    label: Step
                    fields:
                      - name: title
                        label: Title
                        type: string
                      - name: description
                        label: Description
                        type: string
                      - name: number
                        label: Number
                        type: string
          - name: live-demo
            label: Live Demo Invitation
            type: object
            fields:
              - { name: label, label: Label, type: string }
              - { name: id, label: id, type: string }
              - { name: title, label: Title, type: string }
              - { name: subtitle, label: Subtitle, type: string }
              - name: demos
                label: Demo Buttons
                type: block
                list: true
                blocks:
                  - name: demo
                    label: Demo Button
                    fields:
                      - name: title
                        label: Title
                        type: string
                      - name: link
                        label: Link
                        type: string
          - name: testimonials
            label: Testimonials
            type: object
            fields:
              - { name: label, label: Label, type: string }
              - { name: id, label: id, type: string }
              - { name: title, label: Title, type: string }
              - name: testimonials
                label: Testimonials
                type: block
                list: true
                blocks:
                  - name: testimonial
                    label: Testimonial
                    fields:
                      - name: quote
                        label: Quote
                        type: string
                      - name: author
                        label: Author
                        type: string
                      - name: title
                        label: Author Title
                        type: string
                      - name: emoji
                        label: Emoji
                        type: string
          - name: pricing
            label: Pricing Plans
            type: object
            fields:
              - { name: label, label: Label, type: string }
              - { name: id, label: id, type: string }
              - { name: title, label: Title, type: string }
              - { name: subtitle, label: Subtitle, type: string }
              - name: plans
                label: Pricing Plans
                type: block
                list: true
                blocks:
                  - name: plan
                    label: Plan
                    fields:
                      - name: name
                        label: Plan Name
                        type: string
                      - name: devices
                        label: Devices
                        type: string
                      - name: dashboards
                        label: Dashboards
                        type: string
                      - name: alerts
                        label: Alerts
                        type: string
                      - name: export
                        label: Export
                        type: string
                      - name: support
                        label: Support
                        type: string
              - { name: ctaText, label: CTA Text, type: string }
              - { name: ctaLink, label: CTA Link, type: string }
              - { name: compareText, label: Compare Text, type: string }
              - { name: compareLink, label: Compare Link, type: string }
          - name: contact
            label: Contact & Support
            type: object
            fields:
              - { name: label, label: Label, type: string }
              - { name: id, label: id, type: string }
              - { name: title, label: Title, type: string }
              - { name: email, label: Email, type: string }
              - { name: phone, label: Phone, type: string }
              - { name: address, label: Address, type: string }
              - { name: helpTitle, label: Help Centre Title, type: string }
              - name: helpLinks
                label: Help Links
                type: block
                list: true
                blocks:
                  - name: link
                    label: Link
                    fields:
                      - name: title
                        label: Title
                        type: string
                      - name: url
                        label: URL
                        type: string
  - name: components
    label: Components
    type: file
    format: json
    path: "content/components.json"
    fields:
      - { name: anonymousProfileImage, label: Anonymous Profile Image, type: image }
      - { name: logo, label: Logo, type: image }
  - name: navigation
    label: Navigation
    type: file
    format: json
    path: "content/menu.json"
    fields:
      - name: navigation
        label: Navigation
        type: block
        list: true
        blocks:
          - name: navItem
            label: Navigation Item
            fields:
              - { name: title, label: Title, type: string }
              - { name: link, label: Link, type: string }
              - { name: authType, label: Authentication Type, type: select, options: { values: [ "all", "anonymous", "authenticated" ] } }
