media:
  input: public/assets
  output: /assets
  categories: [ "image" ]
content:
  - name: home-page
    label: Home Page
    type: file
    format: json
    path: "content/home-page.json"
    view:
      fields: [ coverImage, title, date ]
    fields:
      - name: sections
        label: Sections
        type: object
        fields:
          - name: hero
            label: Hero Section
            type: object
            fields:
              - { name: title, label: Title, type: string }
              - { name: subtitle, label: Subtitle, type: string }
              - { name: description, label: Description, type: string }
              - { name: image, label: Image, type: image }
              - { name: imageAlt, label: Image Alt, type: string }
              - { name: ctaText, label: CTA Text, type: string }
              - { name: ctaLink, label: CTA Link, type: string }
          - name: functions
            label: Platform Functions
            type: object
            fields:
              - { name: name, label: Name, type: string }
              - { name: title, label: Title, type: string }
              - { name: subtitle, label: Subtitle, type: string }
              - name: features
                label: Features
                type: block
                list: true
                blocks: 
                  - name: feature
                    label: Feature
                    fields:
                      - name: title
                        label: Title
                        type: string
                      - name: description
                        label: Description
                        type: string
                      - name: emoji
                        label: Emoji
                        type: string
              - name: demo
                label: Demo
                type: object
                fields:
                  - { name: ctaText, label: CTA Text, type: string }
                  - { name: description, label: Description, type: string }
                  - { name: accountName, label: Account Name, type: string }
                  - { name: password, label: Password, type: string }
              - { name: image, label: Image, type: image }
              - { name: imageAlt, label: Image Alt, type: string }
              - name: useCase
                label: Use Case
                type: object
                fields:
                  - { name: title, label: Title, type: string }
                  - { name: description, label: Description, type: string }
  - name: components
    label: Components
    type: file
    format: json
    path: "content/components.json"
    fields:
      - { name: anonymousProfileImage, label: Anonymous Profile Image, type: image }
      - { name: logo, label: Logo, type: image }