media:
  input: public/assets
  output: /assets
  categories: [ "image" ]
content:
  - name: home-page
    label: Home Page
    type: file
    format: json
    path: "content/home-page.json"
    view:
      fields: [ coverImage, title, date ]
    fields:
      - name: sections
        label: Sections
        type: block
        list: true
        blocks:
          - name: hero
            label: Hero Section
            type: object
            fields:
              - { name: title, label: Title, type: string }
              - { name: subtitle, label: Subtitle, type: string }
              - { name: description, label: Description, type: string }
              - { name: image, label: Image, type: image }
              - { name: imageAlt, label: Image Alt, type: string }
              - { name: ctaText, label: CTA Text, type: string }
              - { name: ctaLink, label: CTA Link, type: string }
          - name: functions
            label: Platform Functions
            type: object
            fields:
              - { name: name, label: Name, type: string }
              - { name: title, label: Title, type: string }
              - { name: subtitle, label: Subtitle, type: string }
              - name: features
                label: Features
                type: block
                list: true
                blocks: 
                  - name: feature
                    label: Feature
                    fields:
                      - name: title
                        label: Title
                        type: string
                      - name: description
                        label: Description
                        type: string
                      - name: emoji
                        label: Emoji
                        type: string
              - { name: image, label: Image, type: image }
              - { name: imageAlt, label: Image Alt, type: string }
  - name: components
    label: Components
    type: file
    format: json
    path: "content/components.json"
    fields:
      - { name: anonymousProfileImage, label: Anonymous Profile Image, type: image }
      - { name: logo, label: Logo, type: image }
  - name: navigation
    label: Navigation
    type: file
    format: json
    path: "content/menu.json"
    fields:
      - name: navigation
        label: Navigation
        type: block
        list: true
        blocks:
          - name: navItem
            label: Navigation Item
            fields:
              - { name: title, label: Title, type: string }
              - { name: link, label: Link, type: string }
              - { name: authType, label: Authentication Type, type: select, options: { values: [ "all", "anonymous", "authenticated" ] } }